### ISSUE TITLE
Multiple index support

### ISSUE THREAD

**Issue by menardorama** [romansanchez/Calaca#11]
Hi,

I don't know if it's already possible but if not, it would be great to support multiple indexes using wildcard.

I'm thinking about daily index created by logstash for example like it is on kibana : 
[logstash-]YYYY.MM.DD

**Comment by romansanchez** [comment]
You can search across multiple indexes in two ways, leave indexName config blank, or set it to a comma separated list of index names. Same thing for types. Patterns aren't supported.

**Comment by menardorama** [comment]
Thanks but that's not working
