### ISSUE TITLE
Unexpected CSS token: }

### ISSUE THREAD

**Issue by andrewcstewart** [romansanchez/Calaca#13]
I keep getting the following in the debugger.  Dunno it's a big deal but thought I'd report.

```
Unexpected CSS token: }
calaca.css:115
```

**Comment by romansanchez** [comment]
What browser/os are you using?

**Comment by andrewcstewart** [comment]
Safari 8.0.4




If there’s anything in my session info that’d be helpful let me know.

**Comment by romansanchez** [comment]
Yeah line 114 had some extra chars. Fixed it. Thanks.
