### ISSUE TITLE
The plugin doesn't seem installed

### ISSUE THREAD

**Issue by adeschateaux** [romansanchez/Calaca#16]
Hi,

I tried to install the plugin with an unzip in the "plugins" repository, I changed the parameters of config.js.

But when I launch elasticsearch, there is no "Calaca" in the plugin line, do you have any idea of the problem ? 

Regards,

**Comment by romansanchez** [comment]
If not sure where about the plugins structure, just run the plugin install command. It'll be much easier. If you still want to do it manually, the folder structure should look like this: ./elasticsearch-X.X.X/plugins/calaca/_site/

**Comment by adeschateaux** [comment]
Hello Roman,

How can I do to install it with the plugin install command exactly ?

My folder structure is curently calaca-master and then 3 repositories (js,
css and bowser_components) and 5 files (bowser.json, CHANGELOG.md,
index.html, LICENSE and README.md)

Thanks,

2015-06-02 4:22 GMT+02:00 Roman Sanchez <notifications@github.com>:

> If not sure where about the plugins structure, just run the plugin install
> command. It'll be much easier. If you still want to do it manually, the
> folder structure should look like this:
> ./elasticsearch-X.X.X/plugins/calaca/_site/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/romansanchez/Calaca/issues/16#issuecomment-107774421>.
>



-- 
Alexandre DESCHATEAUX
Responsable Commercial - Junior ISEP
Junior Entreprise de l'Institut Supérieur d’Électronique de Paris
28, rue Notre Dame des Champs 75006 PARIS
Tel : 01 42 22 67 44
Port : 06 79 53 00 23

Notre plaquette  : http://www.juniorisep.com/plaquette.pdf
Visitez notre site Internet : http://www.juniorisep.com

*Afin de contribuer au respect de l'environnement, **merci de n'imprimer ce
courriel qu'en cas de nécessité.*

**Comment by romansanchez** [comment]
1) cd into your elasticsearch home dir
2) run bin/plugin -i romansanchez/calaca
3) should now be accessible by visiting url: http://your-host:9200/_plugin/calaca/

**Comment by adeschateaux** [comment]
Hey,

I already tried, that doesn't work for me.

It's written "Failed to install romansanchez, reason: failed to download
out of all possible locations...

You don't know at all how to do without using the command line ?

Thanks,

2015-06-02 14:03 GMT+02:00 Roman Sanchez <notifications@github.com>:

> 1) cd into your elasticsearch home dir
> 2) run bin/plugin -i romansanchez/calaca
> 3) should now be accessible by visiting url:
> http://your-host:9200/_plugin/calaca/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/romansanchez/Calaca/issues/16#issuecomment-107929729>.
>



-- 
Alexandre DESCHATEAUX
Responsable Commercial - Junior ISEP
Junior Entreprise de l'Institut Supérieur d’Électronique de Paris
28, rue Notre Dame des Champs 75006 PARIS
Tel : 01 42 22 67 44
Port : 06 79 53 00 23

Notre plaquette  : http://www.juniorisep.com/plaquette.pdf
Visitez notre site Internet : http://www.juniorisep.com

*Afin de contribuer au respect de l'environnement, **merci de n'imprimer ce
courriel qu'en cas de nécessité.*
