### ISSUE TITLE
Search won't execute

### ISSUE THREAD

**Issue by trident60** [romansanchez/Calaca#17]
Hey Roman!
I'm pretty sure I have everything configured properly…but I'm not a developer or ES expert…but when I go to /_plugin/calaca - and the page opens just like your demo - and type a word in the search box, and hit return, nothing happens.

Running on Ubuntu 14.04, mariadb 10.x, php5.9, 73K posts in the index, ElasticSearch is working fine.

I can see the changes I made in the index file when I reload the page - it appears briefly:

results.post_title (is in red)
results.post_id (in black)

And I edited the .yml as instructed and then researched around, thinking I missed something, and put in the following:

http.cors.enabled: true
http.cors.allow-origin: /.*/  
http.cors.allow-credentials: true 

Any idea what I'm doing wrong?

Thanks for any help!
Rob

**Comment by romansanchez** [comment]
Using the keyboard shortcut Command + Option + J (Mac) or Control + Shift + J (Windows/Linux) to open the Console(in Chrome), do you see any errors being displayed?

**Comment by trident60** [comment]
Very cool - I didn't know about that on the mac - thanks ;)

And yes - connection errors…ah…I had the config.js set to "localhost:9200"!

Changed it to the ip and it works.

But not getting results…not getting any errors! - but no results…like it doesn't see the index.

**Comment by trident60** [comment]
Okay - leaving that screen up it timed out and I saw it - I had the wrong index listed in the "type" section.

**Comment by trident60** [comment]
This is very fast Roman - awesome man, thanks!

I have about a million questions on how to configure the results but I'll contain myself and ask just one - how can I make the results a link? For instance the "post_title" that is coming up results - can that be made clickable/hyperlinked to the article?

Thanks again Roman!

**Comment by romansanchez** [comment]
Absolutely, you can format results however you like. If you want to display your title as a link, you can do something like below.

If your elasticsearch data looks something like this:

```js
{
  "title":"Gravity",
  "url":"http://mybooks.com/gravity"
}
```

then you can modify the index.html to display it like this:
```html
<a href="{result.url}">{result.title}</a>
````

**Comment by trident60** [comment]
Ah - that's easy! So, just to be sure, I can add anything to the results using the {result.sourcename} as long as it's part of the ES document? And it's all easy enough to format…this is slick stuff Roman - thanks again!
Rob

**Comment by romansanchez** [comment]
Yup, that's right.
