### ISSUE TITLE
how to find the type?

### ISSUE THREAD

**Issue by craigcosmo** [romansanchez/Calaca#20]
I'm completely new to ES. Sorry in advance for my illiteracy.

In the readme, it says i need to fill the type. I wonder is that "type"? And how can I find out what type is my ES?

![screen_shot_2015-07-26_at_10_26_02_pm](https://cloud.githubusercontent.com/assets/538657/8894575/cc031b9c-33e5-11e5-9416-341d7716fdc5.png)

**Comment by romansanchez** [comment]
When you make an index request, you specify the type. For example, if your index request looks like this:
```bash
curl -XPOST http://host:9200/index-2015-07-26/maps/123abc
{
...
}
```
then maps would be the type.

**Comment by craigcosmo** [comment]
how many type an index request would have?

And what types are available ?
