### ISSUE TITLE
support for elasticsearch 2 - plugin-descriptor.properties missing

### ISSUE THREAD

**Issue by barthevandoorn** [romansanchez/Calaca#22]
sudo bin/plugin install romansanchez/calaca
-> Installing romansanchez/calaca...
Trying https://github.com/romansanchez/calaca/archive/master.zip ...
Downloading ........................................................................................................................................................................DONE
Verifying https://github.com/romansanchez/calaca/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by ngitter** [comment]
i fixed this issue in a local zip i made, would you like me to upload it?
the fix is:
1. added a plugin-descriptor.properties file in the root.
2. added a _site directory and placed all the files under it, this is to comply the plugin structure.

these fixes work fine for me with ES 2.1.1

**Comment by romansanchez** [comment]
@ngitter Want to make a pull request?

**Comment by xros** [comment]
@ngitter i have the same issue but haven't fixed it. :disappointed:

**Comment by xros** [comment]
Alright, I solved it and did a pull request. Hope you guys can view and enjoy that. :smiling_imp:

**Comment by romansanchez** [comment]
Thanks @xros
