### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by frodopwns** [romansanchez/Calaca#9]
I cloned the repo, followed your configuration instructions:

OPTIONS http://localhost:9200/courses/class/_search net::ERR_CONNECTION_REFUSED

Is there something else i need to do that is left out of the README?

**Comment by frodopwns** [comment]
XMLHttpRequest cannot load http://precise64:9200/courses/class/_search. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://precise64' is therefore not allowed access.

**Comment by frodopwns** [comment]
I guess I need to set this `http.cors.allow-credentials` to true somehow.

**Comment by romansanchez** [comment]
In your elasticsearch.yml config

**Comment by frodopwns** [comment]
Hmm setting that to true didn't help.

**Comment by frodopwns** [comment]
I put this into my elasticsearch.yml:

http.cors.allow-origin: true,
http.cors.allow-methods: true,
http.cors.allow-headers: true,
http.cors.allow-credentials: true,
http.cors.enabled: true

and am still getting

```
precise64/:1 XMLHttpRequest cannot load http://precise64:9200/courses/class/_search. The 'Access-Control-Allow-Origin' header contains the invalid value 'true'. Origin 'http://precise64' is therefore not allowed access.
elasticsearch.angular.min.js:11 ERROR: 2015-02-14T17:35:23Z
  Error: Request error, retrying -- Connection Failure
      at c.error (http://precise64/bower_components/elasticsearch/elasticsearch.angular.min.js:11:25203)
      at f (http://precise64/bower_components/elasticsearch/elasticsearch.angular.min.js:12:198)
      at http://precise64/bower_components/elasticsearch/elasticsearch.angular.min.js:11:20076
      at u (http://precise64/bower_components/angular/angular.min.js:100:258)
      at u (http://precise64/bower_components/angular/angular.min.js:100:258)
      at u (http://precise64/bower_components/angular/angular.min.js:100:258)
      at http://precise64/bower_components/angular/angular.min.js:102:5
      at k.$eval (http://precise64/bower_components/angular/angular.min.js:112:68)
      at k.$digest (http://precise64/bower_components/angular/angular.min.js:109:168)
      at k.$apply (http://precise64/bower_components/angular/angular.min.js:112:398)
```

**Comment by romansanchez** [comment]
Actually, set http.cors.enabled = true

**Comment by romansanchez** [comment]
You're setting true for all properties, which is incorrect. Look at this http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-http.html
to see the values you need to set.

**Comment by frodopwns** [comment]
Yep, this was all I needed:
```
http.cors.allow-origin: '*'
http.cors.enabled: true
```

note to self don't paste from stackoverflow...http://stackoverflow.com/questions/26798518/cors-issue-while-making-ajax-to-elasticsearch-on-aws

Thanks!
